spring:
  profiles:
    default: local

  datasource:
    url: jdbc:h2:tcp://localhost/~/kiosk
    driver-class-name: org.h2.Driver
    username: sa
    password:

---
spring:
  config:
    activate:
      on-profile: local

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true # (2.5~) Hibernate 초기화 이후 data.sql 실행

  h2:
    console:
      enabled: true

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

jwt:
  access:
    secret: "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"
    expiration: 1800000 # 30분

  refresh:
    secret: "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb"
    expiration: 86400000 # 1일