spring:
  config:
    activate:
      on-profile: test

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  sql:
    init:
      mode: never


jwt:
  access:
    secret: testAccessSecretKeydddddddddddddddddddddddddffffffffffffffffffffffff
    expiration: 3600000

  refresh:
    secret: testRefreshSecretKeyaaaaaaaaaaaaaaaaaaaaaaaaaaaaaassssssssssssssssss
    expiration: 86400000


