### 주문 신규 생성
POST localhost:8080/api/orders/new
Content-Type: application/json

{
  "productNumbers": [
    "001",
    "002"
  ]
}

### 날짜 별 주문 조회
GET http://localhost:8080/api/orders/search?startDate=2024-03-20&endDate=2024-03-22&page=0&size=10


